version: "3"
services:
  web:
      image: friendlyhello:latest
      deploy:
          replicas: 5
          resources:
              limits:
                  cpus: "0.1"
                  memory: 50M
          restart_policy:
              condition: on-failure
      ports:
          - "9002:80"
      networks:
          - webnet
networks:
  webnet:
