---
- name: Create webterm dir for gotty
  file:
    path: "/home/{{ username }}/webterm"
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Get gotty binary
  unarchive:
    src: https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz
    dest: "/home/{{ username }}/webterm/"
    remote_src: yes
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Add .gotty config
  copy:
    src: ../templates/.gotty
    dest: "/home/{{ username }}/webterm/"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Check for gotty service start
  shell: pm2 list | grep gotty | grep -o online
  register: gotty_running
  changed_when: False
  ignore_errors: True
  failed_when: no
  become: yes
  become_user: "{{ username }}"

- name: Start gotty with pm2
  command: pm2 start ./gotty -- --config .gotty zsh
  args:
    chdir: "/home/{{ username }}/webterm/"
  become: yes
  become_user: "{{ username }}"
  when: gotty_running.stdout != 'online'
