# vi: set ft=ruby:

Vagrant.configure("2") do |config|
  config.vm.define :dreadbox do |node|
    node.vm.box = 'ubuntu/xenial64'
    node.vm.hostname = 'dreadbox'
    node.vm.network :public_network
    node.vm.provider :virtualbox do |vbox|
      vbox.name = 'dreadbox'
      vbox.memory = 512
      vbox.cpus = 1
    end
  end
end
