# vi: set ft=ruby:

lb = {
  hostname: 'lb',
  box: 'ubuntu/xenial64',
  cpus: '1',
  memory: '512'
}

web1 = {
  hostname: 'web1',
  box: 'ubuntu/xenial64',
  cpus: '1',
  memory: '512'
}

web2 = {
  hostname: 'web2',
  box: 'ubuntu/xenial64',
  cpus: '1',
  memory: '512'
}

data = {
  hostname: 'data',
  box: 'ubuntu/xenial64',
  cpus: '1',
  memory: '512'
}

virtual_machines = [lb, web1, web2, data]

Vagrant.configure("2") do |config|
  virtual_machines.each do |machine|
    config.vm.define machine[:hostname] do |machine_config|
      machine_config.vm.box = machine[:box]
      machine_config.vm.hostname = machine[:hostname]
      machine_config.vm.network :public_network
      machine_config.vm.provider :virtualbox do |vbox|
        vbox.name = machine[:hostname]
        vbox.memory = machine[:memory]
        vbox.cpus = machine[:cpus]
      end
    end
  end
end
