- name: Add user PPAs
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "{{ PPAS }}"
  when: PPAS is defined

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "{{ packages }}"
  when: packages is defined

- name: Check node version
  shell: node --version | grep -oP '\d\d'
  register: node_version
  changed_when: False
  ignore_errors: True
  failed_when: no

- block:
  - name: Get node.js version 10
    get_url:
      url: https://deb.nodesource.com/setup_10.x
      dest: /tmp/
  - name: Execute node setup
    command: bash /tmp/setup_10.x
  when: node_version.stdout != "10" or node_version is failed

- name: Install node
  apt:
    name: nodejs
    state: latest
    update_cache: yes

- name: Install pm2 globaly
  npm:
    name: pm2
    global: yes
