---
- name: Install Apache2
  apt:
    name: apache2
    state: present
    update_cache: True

- name: Enable modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - proxy
    - proxy_http
    - proxy_wstunnel
    - rewrite
    - ssl
  notify:
    - restart apache2
